// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AdCard: typeof import('./src/components/AdCard/index.vue')['default']
    BackBtn: typeof import('./src/components/BackBtn/index.vue')['default']
    Carousel: typeof import('./src/components/Carousel/index.vue')['default']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    Footer: typeof import('./src/components/Footer/index.vue')['default']
    Header: typeof import('./src/components/Header/index.vue')['default']
    Login: typeof import('./src/components/Login/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SCard: typeof import('./src/components/SCard/index.vue')['default']
    SearchBox: typeof import('./src/components/SearchBox/index.vue')['default']
    Selecter: typeof import('./src/components/Selecter/index.vue')['default']
  }
}
