// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AdCard: typeof import('./src/components/AdCard/index.vue')['default']
    BackBtn: typeof import('./src/components/BackBtn/index.vue')['default']
    BackTop: typeof import('./src/components/BackTop/index.vue')['default']
    BuyCard: typeof import('./src/components/BuyCard/index.vue')['default']
    Comment: typeof import('./src/components/Comment/index.vue')['default']
    CommentBox: typeof import('./src/components/Comment/CommentBox.vue')['default']
    CommentList: typeof import('./src/components/Comment/CommentList.vue')['default']
    ContentBox: typeof import('./src/components/Comment/ContentBox.vue')['default']
    Editor: typeof import('./src/components/Editor/index.vue')['default']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    Emoji: typeof import('./src/components/Emoji/index.vue')['default']
    Fold: typeof import('./src/components/Fold/index.vue')['default']
    Footer: typeof import('./src/components/Footer/index.vue')['default']
    Header: typeof import('./src/components/Header/index.vue')['default']
    Icon: typeof import('./src/components/Icon/index.vue')['default']
    Login: typeof import('./src/components/Login/login.vue')['default']
    Operation: typeof import('./src/components/Comment/Operation.vue')['default']
    ReplyBox: typeof import('./src/components/Comment/ReplyBox.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SCard: typeof import('./src/components/SCard/index.vue')['default']
    SearchBox: typeof import('./src/components/SearchBox/index.vue')['default']
    Selecter: typeof import('./src/components/Selecter/index.vue')['default']
    Skeleton: typeof import('./src/components/Skeleton/skeleton.vue')['default']
    Toast: typeof import('./src/components/Toast/index.vue')['default']
    UserInfo: typeof import('./src/components/Comment/UserInfo.vue')['default']
  }
}
